config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :airs
  root 'airs#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

end

app/models/air.rb
class Air < ActiveRecord::Base
    belongs_to :users
    
     has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

ratyrate_rateable "review"



end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :airs
  ratyrate_rater
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
         
   def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
      end
    end     
  
  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.username = auth.info.name   # assuming the user model has a name
    user.avatar = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
  end
end
         

app/controllers/airs_controller.rb
class AirsController < ApplicationController
  before_action :set_air, only: [:show, :edit, :update, :destroy]
  
  # GET /airs
  # GET /airs.json
  def index
    @airs = Air.all
  end

  # GET /airs/1
  # GET /airs/1.json
  def show
  end

  # GET /airs/new
  def new
    @air = Air.new
  end

  # GET /airs/1/edit
  def edit
  end

  # POST /airs
  # POST /airs.json
  def create
    @air = Air.new(air_params)

    respond_to do |format|
      if @air.save
        format.html { redirect_to @air, notice: 'Air was successfully created.' }
        format.json { render :show, status: :created}
      else
        format.html { render :new }
        format.json { render json: @air.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airs/1
  # PATCH/PUT /airs/1.json
  def update
    respond_to do |format|
      if @air.update(air_params)
        format.html { redirect_to @air, notice: 'Air was successfully updated.' }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @air.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airs/1
  # DELETE /airs/1.json
  def destroy
    @air.destroy
    respond_to do |format|
      format.html { redirect_to airs_url, notice: 'Air was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_air
      @air = Air.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def air_params
      params.require(:air).permit(:image, :room_id, :room_name, :location, :description, :price, :accomodation, :bathrooms, :bedrooms, :beds, :room_type, :is_TV, :is_Air_Conditioning, :is_Laptop_friendly_workspace, :is_Washer, :is_Kitchen, :is_WiFi, :is_Family_friendly, :is_Pool, :is_Gym, :is_Wheelchair_accessible, :is_Pets_allowed, :house_rules, :longitude, :latitude)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up) do |user_params|
    user_params.permit({ roles: [] }, :avatay, :email, :fullname, :address, :about, :contactnumber, :username, :password, :password_confirmation)
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/airs_helper.rb
module AirsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/airs/_form.html.erb
<%= form_for @air, html: { multipart: true } do |f| %>
  <% if @air.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@air.errors.count, "error") %> prohibited this air from being saved:</h2>

      <ul>
      <% @air.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :room_id %><br>
    <%= f.number_field :room_id %>
  </div>
  <div class="field">
    <%= f.label :room_name %><br>
    <%= f.text_field :room_name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :accomodation %><br>
    <%= f.number_field :accomodation %>
  </div>
  <div class="field">
    <%= f.label :bathrooms %><br>
    <%= f.number_field :bathrooms %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.number_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :beds %><br>
    <%= f.number_field :beds %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.select :room_type, ['Entire home', 'Private room', 'Shared room'] %>
  </div>
  <div class="field">
    <%= f.label :is_TV %><br>
    <%= f.check_box :is_TV %>
  </div>
  <div class="field">
    <%= f.label :is_Air_Conditioning %><br>
    <%= f.check_box :is_Air_Conditioning %>
  </div>
  <div class="field">
    <%= f.label :is_Laptop_friendly_workspace %><br>
    <%= f.check_box :is_Laptop_friendly_workspace %>
  </div>
  <div class="field">
    <%= f.label :is_Washer %><br>
    <%= f.check_box :is_Washer %>
  </div>
  <div class="field">
    <%= f.label :is_Kitchen %><br>
    <%= f.check_box :is_Kitchen %>
  </div>
  <div class="field">
    <%= f.label :is_WiFi %><br>
    <%= f.check_box :is_WiFi %>
  </div>
  <div class="field">
    <%= f.label :is_Family_friendly %><br>
    <%= f.check_box :is_Family_friendly %>
  </div>
  <div class="field">
    <%= f.label :is_Pool %><br>
    <%= f.check_box :is_Pool %>
  </div>
  <div class="field">
    <%= f.label :is_Gym %><br>
    <%= f.check_box :is_Gym %>
  </div>
  <div class="field">
    <%= f.label :is_Wheelchair_accessible %><br>
    <%= f.check_box :is_Wheelchair_accessible %>
  </div>
  <div class="field">
    <%= f.label :is_Pets_allowed %><br>
    <%= f.check_box :is_Pets_allowed %>
  </div>
  <div class="field">
    <%= f.label :house_rules %><br>
    <%= f.text_area :house_rules %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/airs/edit.html.erb
<h1>Editing Air</h1>

<%= render 'form' %>

<%= link_to 'Show', @air %> |
<%= link_to 'Back', airs_path %>

app/views/airs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Airs</h1>

<% @airs.each do |air| %>
   
     <div class="row">
       <div class="col-sm-6 col-md-4">
         <div class="thumbnail">
           <%= image_tag air.image.url(:medium) %>
             <div class="caption">
                 <h1>Php <%= air.price %> - <%= air.room_name %></h1>
                 <p><%= air.room_type %> - <%= air.beds %> beds</p>
                 <%= rating_for air, 'review' %>
                   <p><a><%= link_to 'Show', air %></a>
                   <a><%= link_to 'Destroy', air, method: :delete, data: { confirm: 'Are you sure?' } %></a></p>
             </div>
         </div>
       </div>
     </div>

    <% end %>

<br>

<%= link_to 'New Air', new_air_path %>

app/views/airs/new.html.erb
<h1>New Air</h1>

<%= render 'form' %>

<%= link_to 'Back', airs_path %>

app/views/airs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 <%= image_tag @air.image.url(:medium) %>
</p>

<p>
 <strong>Room name:</strong>
 <%= @air.room_name %>
</p>

<p>
 <strong>Location:</strong>
 <%= @air.location %>
</p>

<p>
 <strong>Longitude:</strong>
 <%= @air.longitude %>
</p>

<p>
 <strong>Latitude:</strong>
 <%= @air.latitude %>
</p>

<p>
 <strong>Description:</strong>
 <%= @air.description %>
</p>

<p>
 <strong>Price:</strong>
 <%= @air.price %>
</p>

<p>
 <strong>Accomodation:</strong>
 <%= @air.accomodation %>
</p>

<p>
 <strong>Bathrooms:</strong>
 <%= @air.bathrooms %>
</p>

<p>
 <strong>Bedrooms:</strong>
 <%= @air.bedrooms %>
</p>

<p>
 <strong>Beds:</strong>
 <%= @air.beds %>
</p>

<p>
 <strong>Room type:</strong>
 <%= @air.room_type %>
</p>

<p>
 <strong>TV:</strong>
 <%= @air.is_TV %>
</p>

<p>
 <strong>Air conditioning:</strong>
 <%= @air.is_Air_Conditioning %>
</p>

<p>
 <strong>Laptop friendly workspace:</strong>
 <%= @air.is_Laptop_friendly_workspace %>
</p>

<p>
 <strong>Washer:</strong>
 <%= @air.is_Washer %>
</p>

<p>
 <strong>Kitchen:</strong>
 <%= @air.is_Kitchen %>
</p>

<p>
 <strong>WiFi:</strong>
 <%= @air.is_WiFi %>
</p>

<p>
 <strong>Family friendly:</strong>
 <%= @air.is_Family_friendly %>
</p>

<p>
 <strong>Pool:</strong>
 <%= @air.is_Pool %>
</p>

<p>
 <strong>Gym:</strong>
 <%= @air.is_Gym %>
</p>

<p>
 <strong>Wheelchair accessible:</strong>
 <%= @air.is_Wheelchair_accessible %>
</p>

<p>
 <strong>Pets allowed:</strong>
 <%= @air.is_Pets_allowed %>
</p>

<p>
 <strong>House rules:</strong>
 <%= @air.house_rules %>
</p>
review  : <%= imdb_style_rating_for @air, current_user %>

 <div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: <%= @air.latitude %>, lng: <%= @air.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDN9Pw5eIEneIYp24g7EW5-iQ7oadtlRD4&callback=initMap">
    </script>

<%= link_to 'Edit', edit_air_path(@air) %> |
<%= link_to 'Back', airs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= csrf_meta_tags %>
      <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDN9Pw5eIEneIYp24g7EW5-iQ7oadtlRD4&callback=initMap">
    </script>

</head>
<body>

<% if user_signed_in? %>
          <li> <%= link_to 'Settings', edit_user_registration_path, :class => 'navbar-link' %></li>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
        <% else %>
          <li>  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>  </li>
          <li> <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
          <li>  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>  </li>
        <% end %>

<%= yield %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p><%= current_user.username %></p>
<%= image_tag current_user.avatar %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>